services:
  bbx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - .env
      - .bank-001.env
    depends_on:
      db: 
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  cter:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    env_file:
      - .env
      - .bank-002.env
    depends_on:
      db: 
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: postgres:13-alpine
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      #- POSTGRES_DB=nest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s  
